DROP TABLE IF EXISTS general_desc CASCADE;

DROP TABLE IF EXISTS general_type CASCADE;

DROP TABLE IF EXISTS enrollments CASCADE;

DROP TABLE IF EXISTS lessons CASCADE;

DROP TABLE IF EXISTS courses CASCADE;

DROP TABLE IF EXISTS user_profiles CASCADE;

DROP SEQUENCE IF EXISTS users_id_seq;

DROP TABLE IF EXISTS users CASCADE;