CREATE TABLE IF NOT EXISTS general_type (
    gdtype TEXT NOT NULL,
    name_local TEXT,
    name_eng TEXT,
    status CHAR(1) DEFAULT 'A' CHECK (status IN ('A', 'I')),
    create_date TIMESTAMPTZ DEFAULT NOW(),
    create_user TEXT,
    modify_date TIMESTAMPTZ DEFAULT NOW(),
    modify_user TEXT,
    PRIMARY KEY (gdtype)
);

CREATE TABLE IF NOT EXISTS general_desc (
    id integer NOT NULL,
    gdtype TEXT NOT NULL,
    gdcode TEXT NOT NULL,
    desc1 TEXT,
    desc2 TEXT,
    desc3 TEXT,
    desc4 TEXT,
    desc5 TEXT,
    cond1 TEXT,
    cond2 TEXT,
    cond3 TEXT,
    cond4 TEXT,
    cond5 TEXT,
    status CHAR(1) DEFAULT 'A' CHECK (status IN ('A', 'I')),
    create_date TIMESTAMPTZ DEFAULT NOW(),
    create_user TEXT,
    modify_date TIMESTAMPTZ DEFAULT NOW(),
    modify_user TEXT,
    foreign key (gdtype) references general_type (gdtype) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (id)
);

CREATE SEQUENCE users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL DEFAULT nextval('users_id_seq'),
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_profiles (
    id INT NOT NULL,
    bio TEXT,
    birth_date DATE,
    user_id INT NOT NULL UNIQUE REFERENCES users (id),
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS courses (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    duration_minutes INT NOT NULL,
    course_id INT NOT NULL REFERENCES courses (id),
    CONSTRAINT pk_lesson PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS enrollments (
    user_id INT NOT NULL REFERENCES users (id),
    course_id INT NOT NULL REFERENCES courses (id),
    enrolled_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, course_id)
);