@DotnetEFProject.Api_HostAddress = http://localhost:44324

GET {{DotnetEFProject.Api_HostAddress}}/api/UserQuery/GetUserList
Accept: application/json

###

GET {{DotnetEFProject.Api_HostAddress}}/api/UserQuery/GetUser?Id=1
Accept: application/json